# --- CONFIGURACIÓN CORREGIDA ---

# 1. ACCESO:
# Permitimos localhost para que tu prueba funcione, y también la red interna.
rocommunity public 127.0.0.1
rocommunity public 10.128.0.0/9

# 2. VINCULACIÓN:
# OJO AQUÍ: Apuntamos al script .sh, NO al .txt
extend estado_ia /bin/bash /home/ayipeton/Trabajo-GAR/monitor_ia.sh


